--- #YAML:1.0
name:                Geo-Coder-Yahoo
version:             0.03_51
abstract:            Geocode addresses with the Yahoo! API 
license:             perl
author:              
    - Ask Bjoern Hansen <ask@develooper.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    LWP::UserAgent:                0
    Test::More:                    0
    URI:                           0
    Yahoo::Search::XML:            20060729.004
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
